#!/bin/sh
set -ex

[ "$(ocamlopt --version)" = 4.14.2 ]
autoconf
./configure --prefix=$PWD/_install --enable-runtime5 --enable-middle-end=flambda2 --enable-poll-insertion --disable-naked-pointers --enable-oxcaml-dwarf --enable-name-mangling=RunLengthEncoding
make
